defaults:
  - lerobot

# Group G06
# Datasets: 1
# Feature Shapes:
#   - actions.left_ee_to_left_armbase_pose: [7]
#   - actions.left_ee_to_robot_pose: [7]
#   - actions.left_gripper.position: [1]
#   - actions.left_joint.position: [6]
#   - actions.left_tcp_to_left_armbase_pose: [7]
#   - actions.left_tcp_to_robot_pose: [7]
#   - actions.right_ee_to_right_armbase_pose: [7]
#   - actions.right_ee_to_robot_pose: [7]
#   - actions.right_gripper.position: [1]
#   - actions.right_joint.position: [6]
#   - actions.right_tcp_to_right_armbase_pose: [7]
#   - actions.right_tcp_to_robot_pose: [7]
#   - episode_index: [1]
#   - frame_index: [1]
#   - hand_left_camera_intrinsics: [4]
#   - hand_left_camera_to_robot_extrinsics: [7]
#   - hand_right_camera_intrinsics: [4]
#   - hand_right_camera_to_robot_extrinsics: [7]
#   - head_camera_intrinsics: [4]
#   - head_camera_to_robot_extrinsics: [7]
#   - images.rgb.hand_left: [480, 640, 3]
#   - images.rgb.hand_right: [480, 640, 3]
#   - images.rgb.head: [480, 640, 3]
#   - index: [1]
#   - master_actions.left_gripper.openness: [1]
#   - master_actions.left_gripper.position: [1]
#   - master_actions.left_joint.position: [6]
#   - master_actions.right_gripper.openness: [1]
#   - master_actions.right_gripper.position: [1]
#   - master_actions.right_joint.position: [6]
#   - states.left_ee_to_left_armbase_pose: [7]
#   - states.left_ee_to_robot_pose: [7]
#   - states.left_gripper.position: [1]
#   - states.left_joint.position: [6]
#   - states.left_tcp_to_left_armbase_pose: [7]
#   - states.left_tcp_to_robot_pose: [7]
#   - states.right_ee_to_right_armbase_pose: [7]
#   - states.right_ee_to_robot_pose: [7]
#   - states.right_gripper.position: [1]
#   - states.right_joint.position: [6]
#   - states.right_tcp_to_right_armbase_pose: [7]
#   - states.right_tcp_to_robot_pose: [7]
#   - states.robot_to_env_pose: [7]
#   - task_index: [1]
#   - timestamp: [1]
lerobot_dir: "mydata"
repo_id:
  - "InternData-A1-full/sim_updated_lerobotv30/basic_tasks/acone/fold_the_blue_shirt/fold_the_blue_shirt"